import type { Metadata } from "next";
import Aside from "@/components/aside";

export const metadata: Metadata = {
  title: "Components - Lunastra Ui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-auto px-8 w-screen flex-1 items-start justify-center flex gap-10">
      <Aside />
      {children}
    </div>
  );
}
