import type { Metadata } from "next";
import Aside from "@/components/aside";

export const metadata: Metadata = {
    title: "Components - Lunastra Ui",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="mx-auto px-8 w-[1400px] flex-1 items-start flex gap-10">
            <Aside />
            {children}
        </div>
    );
}
