import type { Metadata } from "next";
import Aside from "@/components/aside";
import "./globals.css";


export const metadata: Metadata = {
  title: "Lunastra Ui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div className="pt-20">
          <div className="mx-auto px-8 w-[1400px] flex-1 items-start flex gap-10">
            <Aside />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
